name: updateSwaggerJSON

on:
  push:
    branches: [ main ]
 #   paths:
 #     - '**.js'

jobs:
  updateSwaggerJSON:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: export TZ="Asia/Tokyo"
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: nohup npm run start &
    
    - name: Get api-docs.json
      run: |
        cd ./docs 
        rm ./api-docs.json 
        wget http://127.0.0.1:3000/api-docs.json

    - run: git status -s
    
    - run: "[[ `git status -s` =~ .*api-docs.* ]]"
    
    - name: check api-docs.json update
      if: ${{ $? }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update api-docs.json" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
