# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: updateSwaggerJSON

on:
  push:
    branches: [ main ]
#    paths:
#      - '**.js'

jobs:
  updateSwaggerJSON:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: export TZ="Asia/Tokyo"
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: nohup npm run start &
    
    - run: cd ./docs 
        && rm ./api-docs.json 
        && wget http://127.0.0.1:3000/api-docs.json

    - run: ls -la

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update api-docs.json" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
